POST https://phonebook-backend-8jmd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Beatrice Rogojan Puff", 
    "number": "12345678917"
}

###

GET https://phonebook-backend-8jmd.onrender.com/